### ISSUE TITLE
[nb_anacondacloud] Integration Tests on anaconda build (Win)

### ISSUE THREAD

**Issue by bollwyvl** [Anaconda-Platform/anaconda-nb-extensions#128]
This needs integration tests.

- [x] Get working locally
- [ ] Anaconda Build?

PR here: https://github.com/Anaconda-Server/nb_anacondacloud/pull/8

**Comment by bollwyvl** [comment]
Over on Anaconda-Server/nb_anacondacloud#8, I've made some progress towards actually testing the UI.

Right now, I'm getting to the login screen. I think I need to pass some more information to casper, perhaps, to pull the right location for my user credentials.

**Comment by bollwyvl** [comment]
Just got the first running test (fail) on Anaconda Cloud:

http://anaconda.org/nbcio/nb_anacondacloud/builds/6/0

> They can't all be winners, kid :pill:

The issue is now that I am mocking the response to various requests to the anaconda API, and the unauthenticated test path (previously the thing easiest to test!) is always coming up authenticated. I'll be addressing that presently, either by doing an "authenticated" and "unauthenticated" run, with different mocks in place, but preferably some more clever approach.

**Comment by stephenakearns** [comment]
Dependency - waiting to get xvfb on build machines. 
(build is working, but automted unit tests failing because of this)
IT-Help #1868: xvfb on build-binstar-continuum linux-64

**Comment by ijstokes** [comment]
@bollwyvl Is this resolved?  I see that PR #8 is merged, and that nb_anacondacloud `master` is building successfully on Anaconda Build.

**Comment by stephenakearns** [comment]
Working on linux/mac, but not Windows. Work with Ian Henriksen to resolve.

**Comment by damianavila** [comment]
From my understanding, this is working now... but maybe I am missing something. Can you confirm @bollwyvl?
