### ISSUE TITLE
Diff: provide basic visual diff functionality for two notebooks (on Anaconda Cloud?)

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Platform/anaconda-nb-extensions#134]
## Goals
* [ ] client-side functionality
* [ ] needs access to the HTML, *.ipynb file
* [ ] diff is a long-running (scheduled, async) task

## Work steps
* [ ] confirm requirements
* [ ] wireframe
* [ ] tech design
* [ ] build and document
* [ ] test 

Question: is this going to be OSS or Commercial work? 

Current work: https://github.com/bollwyvl/nbdiffstream

**Comment by stephenakearns** [comment]
closing as dupe of #137

**Comment by damianavila** [comment]
You did not close the issue and I think you are wrong about the dupe... this is diff, the other one is themes...

**Comment by damianavila** [comment]
It would be nice to link the relevant discussions happening/happened in nb_delta repo... @stephenakearns @bollwyvl
