### ISSUE TITLE
Final smoke test against the final 4.2 released version

### ISSUE THREAD

**Issue by damianavila** [Anaconda-Platform/anaconda-nb-extensions#142]
ref #130

**Comment by damianavila** [comment]
AFAIK, it was done. So closing here.

**Comment by bollwyvl** [comment]
Yeah, wasn't sure if we wanted at least one other person who hadn't been
building all this stuff try it out... but works for me :)

**Comment by damianavila** [comment]
I will test it during the weekend/next week, but pretty confident with your testing to actually close it :wink:
