### ISSUE TITLE
Migration to the new mechanism to install and enable extensions in 4.2

### ISSUE THREAD

**Issue by damianavila** [Anaconda-Platform/anaconda-nb-extensions#148]
We need to migrate all of our extensions.

**Comment by damianavila** [comment]
When upstream notebook PR 879 is merged, we need to migrate our extensions.
This is a branch on nb_conda_kernels where you can see the changes needed to make it work: https://github.com/Anaconda-Server/nb_conda/pull/12

**NOTE**: if the PR change a little bit, maybe there are some additional changes to do, but pretty sure it will be minimal and easy to handle. Additionally, there are probably some other thing to clean in the extension because we are not using nb_config_manager nor nbsetuptools anymore...

pinging @mmarchetti and @malev, so they are aware of the changes needed.

**Comment by damianavila** [comment]
* [ ] https://github.com/Anaconda-Server/nb_conda_kernels/pull/20
* [ ] https://github.com/Anaconda-Server/nb_conda/pull/12
* [ ] https://github.com/Anaconda-Server/nbpresent/pull/64

**Comment by bollwyvl** [comment]
> Anaconda-Platform/nb_anacondacloud#21

This is looking pretty good. I've successfully built and tested on osx, linux and windows with my home-made package of notebook 4.2, created from the PyPi package... which appears to be the approach taken by the anaconda official package, which is also underway.

**Comment by bollwyvl** [comment]
> Anaconda-Platform/nb_conda_kernels#20

In progress, builds are running. Trying local windows build.

**Comment by bollwyvl** [comment]
Updated all of the builds to use `notebook` from `defaults`. If/when these all build:
- i'll do a `dev`-labeled release
- update this-a-here metapackage
- do a bunch of local testing
- upload real extensions
- update the metapackage

Probably forgot some stuff...

**Comment by damianavila** [comment]
Sounds like a good plan to me!

**Comment by bollwyvl** [comment]
Ok, did one last beta of nb_conda. Looks good with the metapackage on win/linux/osx.

Going to go ahead and do the actual releases.

**Comment by damianavila** [comment]
:+1:

**Comment by bollwyvl** [comment]
All packages are uploaded to `anaconda-nb-extensions/main` except for a few linux stragglers:
- https://anaconda.org/anaconda-nb-extensions/anaconda-nb-extensions/files?version=1.0.0
- https://anaconda.org/anaconda-nb-extensions/nb_anacondacloud/files?version=1.0.0
- https://anaconda.org/anaconda-nb-extensions/nb_conda_kernels/files?version=1.0.0
- https://anaconda.org/anaconda-nb-extensions/nb_conda/files?version=1.0.0
- https://anaconda.org/anaconda-nb-extensions/nbpresent/files?version=3.0.0

I'll move the stragglers as they appear, then start merging and closing things...

**Comment by stephenakearns** [comment]
Hi @bollwyvl and @damianavila - I think this issue is completed/obsolete - closing this, but feel free to reopen with comments about remaining work.
